### ISSUE TITLE
How do I enable tracing of TLM transactions?

### ISSUE THREAD

**Issue by mohamed** [machineware-gmbh/vcml#45]
When I pass `--trace-stdout`, I don't see any TLM traces being printed to the `stdout` despite the simulation having many `read` transactions. Do I have to enable something explicitly to obtain these traces?

**Comment by janweinstock** [comment]
You also need to specify the module you want to trace: `-c <module>.trace=1`, e.g. `-c system.my_uart.trace=1`. You can also trace individual ports: `-c system.my_uart.irq.trace=1`. To trace everything, you could do `-c system.trace=1`.

**Comment by mohamed** [comment]
Thanks a lot @janweinstock for your answer. I see now indeed TLM transactions. However, I only see the first transaction at time `t=0`. After that, I don't see any TLM traces. See below:

```
[I 0.000000000] dut.mcu: Fetching insn for PC = 0x0000ef53
[TLM 0.000000000] dut.mcu.insn     >> RD 0x0000ef53 [fc 7f 00 00] (TLM_INCOMPLETE_RESPONSE)
[TLM 0.000000000] dut.mcu.insn     << RD 0x0000ef53 [00 00 00 00] (TLM_OK_RESPONSE)
[I 0.000000000] dut.dsp: Fetching insn for PC = 0x00008eeb
[TLM 0.000000000] dut.dsp.insn     >> RD 0x00008eeb [fc 7f 00 00] (TLM_INCOMPLETE_RESPONSE)
[TLM 0.000000000] dut.dsp.insn     << RD 0x00008eeb [00 00 00 00] (TLM_OK_RESPONSE)
[I 0.000000010] dut.mcu: Fetching insn for PC = 0x00008f1c
[I 0.000000010] dut.dsp: Fetching insn for PC = 0x0000abc2
[I 0.000000020] dut.mcu: Fetching insn for PC = 0x0000b835
[I 0.000000020] dut.dsp: Fetching insn for PC = 0x00007e14
[I 0.000000030] dut.mcu: Fetching insn for PC = 0x0000c33b
[I 0.000000030] dut.dsp: Fetching insn for PC = 0x00008a23
```

**Comment by mohamed** [comment]
Never mind. I found that `allow_dmi` is set to `true` for `memory`. This causes it to switch to DMI after the first transaction. Upon disabling DMI, it works as expected
