### ISSUE TITLE
ui::vnc crashes when setup() is followed by render() early

### ISSUE THREAD

**Issue by shesselba** [machineware-gmbh/vcml#74]
ui::vnc::setup() creates the vnc server screen at m_screen which is used by ui::vnc::render() to mark the screen rectangle as modified. However, m_screen is created in a separate thread and there is no protection to ensure m_screen has been initialized before using it.

Protect rendering by using the currently unused m_mutex and a condition_variable to wait for the vnc server to be properly set up.

[0001-ui-vnc-wait-for-server-setup-before-rendering.patch.txt](https://github.com/machineware-gmbh/vcml/files/13442798/0001-ui-vnc-wait-for-server-setup-before-rendering.patch.txt)

**Comment by janweinstock** [comment]
Thanks for the report. Can you check if 4f025dd fixes your issue and let me know?

**Comment by shesselba** [comment]
Yes it does. Thanks a lot.
