### ISSUE TITLE
GPIO Binding should support sc_signal

### ISSUE THREAD

**Issue by aut0** [machineware-gmbh/vcml#77]
gpio_bind() does not support binding sc_signal eventhough VCML GPIO protocol is capable of supporting this.

**Comment by codesnish** [comment]
does this mean that 

1. Model files of gpio do not have bind support, whereas protocol files do ?

2. And hence the files located at :- 

- `include/vcml/models/generic/gpio.h`
- `src/vcml/models/generic/gpio.cpp`

need to be updated with bind support??
