### ISSUE TITLE
too many main() routines?

### ISSUE THREAD

**Issue by soundart** [machineware-gmbh/vcml#83]
Hi,

my avp64 based design did not start today.

After some debugging I found, that there is a second main()  routine  from

systemc-src/src/sysc/kernel/sc_main.cpp

```
int
main( int argc, char* argv[] )
{
        return sc_core::sc_elab_and_sim( argc, argv );
}
```

The one I want (because I can then specify vcml properties) is from here:

vcml/src/vcml/core/setup.cpp
```
extern "C" {

#ifndef MWR_MSVC
MWR_DECL_WEAK
#endif
int main(int argc, char** argv) {
    return vcml::main(argc, argv);
}
}
```

I was experimenting with another linker "mold" today and that probably  exposed the problem.

```
find_program(MOLD mold)
if(MOLD)
    add_link_options("-fuse-ld=mold")
endif()
```

However I am not sure that the current setup in vcml is deterministic. 

libsystemc.a is a public link dependency of vcml. 

So the linker of the final executable has always two main routines:
- a weak extern "C" main() from vcml 
- a global "CPLUSPLUS" main() from systemc

As the one from vcml is "weak", why was it used with the normal linker?

**Comment by janweinstock** [comment]
Hi,

both VCML and SystemC provide their own `main` routines; which one gets used is linker specific, but usually (for GCC and clang on Linux), it should pick the main routine from the first library or object file on the command line. I assume `mold` has a different behavior and ends up using the one from SystemC. 

To be really sure that the correct `main` gets called, you can just define your own one and call `vcml::main` from there. The one from SystemC should just be discarded by the linker (it is defined in its own object file and has no other symbols that are needed for linking), and the one from VCML is weak, so it should not get in the way.

**Comment by soundart** [comment]
Hi thank you, very interesting. 

Mold tries to be independant of the left and right processing order: 
https://github.com/rui314/mold/blob/main/docs/mold.md#archive-symbol-resolution

I think I will try to add my own main into an object file which has to be used anyway to increase robustness.
And place it very leftish on the cmd line. Do I have to make it extern "C" main(..) or not? 

Basically I do not have to "overwrite" weak extern "C" main() from vcml. It is alread ok. 
The one non-weak symbol from SystemC has to be avoided, or? An error message from the linker "duplicate symbol" is ok too for me.

My workaround uptonow was to patch the SystemC CMakeLists and remove the   sysc/kernel/sc_main.cpp
